# Copyright 2026 James Casey
# SPDX-License-Identifier: Apache-2.0

[package]
name = "yaml"
version = "0.1.1"
description = "YAML parsing and generation for Beamtalk"

[dependencies]

[native.dependencies]
yamerl = "0.10.0"
